# Generated by Django 4.2.21 on 2025-05-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genre_alter_book_cover_url_alter_book_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('audio_file', models.FileField(help_text='Generated music clip for this book+tag', upload_to='book_music/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='api.book')),
            ],
        ),
    ]
