# Generated by Django 4.2.21 on 2025-05-26 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_book_author_alter_book_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'music')},
            },
        ),
    ]
