# Generated by Django 4.2.21 on 2025-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_musicreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='similar_books',
            field=models.ManyToManyField(blank=True, help_text='상위 4권의 유사 도서', related_name='recommended_for', to='api.book'),
        ),
    ]
