# Generated by Django 4.2.21 on 2025-05-26 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommended_books',
            field=models.ManyToManyField(blank=True, help_text='유사도 상위 N권을 미리 저장', to='api.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Upstage 임베딩 벡터', null=True, size=None),
        ),
    ]
