# Generated by Django 4.2.21 on 2025-05-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_recommended_books_alter_book_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
